# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
#       - name: "update" 
#         uses: actions/checkout@v3
      - run: git clone https://github.com/akunowski/test_test
      - run: ls
      - run: cd test_test
      - run: ls
      - run: pwd

      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com

      - run: git status  
      - run: git fetch --all
      - run: git status
     
      - run: git checkout main
      - run: git pull
      - run: cat main.txt]
      
      - run: git checkout bb
      - run: cat main.txt]
      - run: git pull
      - run: git status
      
      - run: git remote main
      - run: git status
      - run: git push -f
